/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function HatModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/hat-transformed.glb");

  const modelRef = useRef();
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  
  // スマホサイズの時は位置を上に、サイズを小さく
  const scale = isMobile ? [10, 10, 10] : [13, 13, 13];
  const position = isMobile ? [0, 3, 0] : [0, 0, 0];
  
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={scale}
      rotation={[0.4, -1, 0]}
      position={position}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        position={[0, -3.867, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
});

export default HatModel;
useGLTF.preload("/models/hat-transformed.glb");
